System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at ....Resolve(IAssemblyReference , String )
   at ....Resolve(IAssemblyReference , String )
   at ..Load(IAssemblyReference , String )
   at Reflector.CodeModel.Memory.AssemblyReference.Resolve()
   at ..(ITypeReference )
   at ..Resolve()
   at ....(IType )
   at ....(IExpression , IType )
   at ....(IAssignExpression )
   at ..(IExpression )
   at ..(IExpressionStatement )
   at ..(IStatement )
   at ..(IStatementCollection )
   at ..(IBlockStatement )
   at ..(IStatement )
   at ..(ITryCatchFinallyStatement )
   at ..(IStatement )
   at ..(ILabeledStatement )
   at ..(IStatement )
   at ..(IStatementCollection )
   at ..(IBlockStatement )
   at ..(IStatement )
   at ..(IMethodDeclaration )
   at ....(IMethodDeclaration )
   at ....(IMethodDeclaration )
   at ..(IMethodDeclaration )
   at ..(IMethodDeclaration )
   at ..(IMethodDeclarationCollection )
   at ..(ITypeDeclaration )
   at ..TranslateTypeDeclaration(ITypeDeclaration , Boolean , Boolean )
   at ..WriteTypeDeclaration(ITypeDeclaration , String , ILanguageWriterConfiguration )
namespace Winista.Text.HtmlParser.Util
{
}

